### ISSUE TITLE
Benchmark against other libraries

### ISSUE THREAD

**Issue by indutny** [indutny/fft.js#1]
This library is most likely one of the fastest implementations of Cooley-Tukey FFT algorithm. It would be interesting to see how it compares to other JS implementations.

**Comment by indutny** [comment]
Added "framework" for introducing more benchmarks. Right now comparing to:

* [fft][0]
* [dsp.js][1]
* [fourier][2]

[0]: https://www.npmjs.com/package/fft
[1]: https://github.com/corbanbrook/dsp.js
[2]: https://github.com/drom/fourier

**Comment by drom** [comment]
try https://github.com/drom/fourier

https://github.com/drom/fourier/issues/1

**Comment by indutny** [comment]
@drom done

**Comment by faroit** [comment]
Hey, this is a great implementation! 

Have you tested compared to the builtin FFT in web audio? Even though this would be bit unfair because it's not js, it would still be interesting to see if fft.js would be fast enough to use this for realtime audio.

**Comment by indutny** [comment]
@faroit good idea!

Just curious, how many bands do you actually use in web audio? fft.js can do 2k ops/sec on 16384 bands, which means that it will add less than 0.5ms of latency. On 4096 bands it is about 0.1ms of added latency.

**Comment by humphd** [comment]
+@corbanbrook who worked on the Firefox Audio stuff with me and wrote dsp.js. He's done a lot of perf work on this stuff in the past, see also https://gist.github.com/corbanbrook/469c325734e458ba1415509f52d9c096

**Comment by indutny** [comment]
This gist is a part of our discussion with @corbanbrook with regards to fft.js performance and comparing it to dsp.js . After few improvements to benchmarks and the library code, I'm quite confident that current benchmarks are accurate and fft.js outperforms dsp.js on all of input sizes.

**Comment by indutny** [comment]
Thank you for adding it to this discussion, though!

**Comment by Matt-Esch** [comment]
https://github.com/Matt-Esch/browser-fft/blob/master/index.js an example using the browser "native" fft with a web audio hack

**Comment by indutny** [comment]
@Matt-Esch this is cool, however it is rather non obvious how the latency can be measured with WebAudio. I suppose one can insert JS node before and after and calculate delta, but this is obviously not how this is going to be used.

**Comment by indutny** [comment]
I guess this can be closed now.
