### ISSUE TITLE
number-theoretic transform?

### ISSUE THREAD

**Issue by benediamond** [indutny/fft.js#12]
hey @indutny,

incredible work as always.

I'm wondering if you've considered implementing the [number-theoretic transform](https://en.wikipedia.org/wiki/Discrete_Fourier_transform_(general)#Number-theoretic_transform)---i.e. the FFT in a prime field `F_q` which admits high-order 2-adic roots of unity. There's also a version where the input "signal" is a vector of points on an elliptic curve E(F_p) of order `q`.

For example, consider the elliptic curve `altbn_128`, used in Ethereum precompiles---see [here](https://github.com/AztecProtocol/AZTEC/blob/master/packages/aztec.js/src/bn128/index.js) for an implementation built off your [elliptic](https://github.com/indutny/elliptic) package. See [herumi / ate-pairing](https://github.com/herumi/ate-pairing) for more details (it's called "CurveSNARK" there).

The order `q` of this curve is such that the field `F_q` admits `2^n`-order modular-multiplicative roots of unity for `n` as high as 28. Thus one can take FFTs of power-of-2-length vectors consisting _either_ of elements of `F_q` _or_ of curve points.

Of course this isn't hard to implement manually but I'd enjoy your optimizations. Also happy to contribute if you'd be interested in going this direction.

**Comment by indutny** [comment]
Hello!

Thank you for kind words.

I have not considered implementing FFT over a field, as I never had a use of it.

Sorry!
